# Program to decompose a matrix using Cholesky Decomposition

#### python 3

## About Cholesky Decomposition:
* In linear algebra, the Cholesky decomposition or Cholesky factorization is a decomposition of a Hermitian, positive-definite matrix into the product of a lower triangular matrix and its conjugate transpose, which is useful for efficient numerical solutions, e.g., Monte Carlo simulations.

In [1]:
import numpy as np
import math

In [53]:
# Get lower triangular matrix
def get_lower_triangular_matrix(npMatrix):
    
    lower = [[0 for x in range(n)]
                for y in range(n)]
    
    for i in range(n):
        for j in range(i + 1):
            sum1 = 0
 
            # summation for diagonals
            if (j == i):
                for k in range(j):
                    sum1 += pow(lower[j][k], 2)
                lower[j][j] = int(math.sqrt(npMatrix[j][j] - sum1))
            else:
                 
                # Evaluating L(i, j)
                # using L(j, j)
                for k in range(j):
                    sum1 += (lower[i][k] *lower[j][k])
                if(lower[j][j] > 0):
                    lower[i][j] = int((npMatrix[i][j] - sum1) /
                                               lower[j][j])
    return np.array(lower)


def Cholesky_Decomposition(npMatrix, n):
     
    print("Input Matrix is:\n", npMatrix)

    # Decomposing a matrix into Lower Triangular
    lower=get_lower_triangular_matrix(npMatrix)
    
    # Displaying Lower Triangular and its Transpose
    print("Lower Triangular matrix is:\n", lower)
    print("Transpose:\n", lower.transpose())

In [6]:
n = 3;
matrix = [[4, 12, -16],
          [12, 37, -43],
          [-16, -43, 98]];

Cholesky_Decomposition(matrix, n)

Lower Triangular		Transpose
2	0	0		2	6	-8	
6	1	0		0	1	5	
-8	5	3		0	0	3	


In [36]:
type(matrix)

list

In [54]:
n = 3;
matrix = [[4, 12, -12],
          [12, 37, -43],
          [-16, -43, 98]];

Cholesky_Decomposition(matrix, n)

Input Matrix is:
 [[4, 12, -12], [12, 37, -43], [-16, -43, 98]]
Lower Triangular matrix is:
 [[ 2  0  0]
 [ 6  1  0]
 [-8  5  3]]
Transpose:
 [[ 2  6 -8]
 [ 0  1  5]
 [ 0  0  3]]


In [25]:
# Rank of the matrix
np.linalg.matrix_rank(np.array(matrix))

3

## Calculate lower and upper triangle

In [57]:
a = np.array([[4 , 1 , -1],
              [1 , 2 , 1],
              [-1 , 1 , 2]])

npLower = get_lower_triangular_matrix(a)
npLower

array([[2, 0, 0],
       [0, 1, 0],
       [0, 1, 1]])

In [70]:
a = np.array([[4 , 1 , -1],
              [1 , 2 , 1],
              [-1 , 1 , 2]])

#Lower Triangle L
L=np.tril(a)
L

array([[ 4,  0,  0],
       [ 1,  2,  0],
       [-1,  1,  2]])

In [71]:
# Calculation of Determinant of Lower Triangle L
np.linalg.det(L) > 0

True

In [69]:
U=np.triu(a)
U

array([[ 4,  1, -1],
       [ 0,  2,  1],
       [ 0,  0,  2]])

## Reference:
1. https://www.geeksforgeeks.org/cholesky-decomposition-matrix-decomposition/