# Program that randomly generates a positive definite matrix and then verifies it is by using Sylvester’s criterion.

## About Sylvester's Criteria: 



* In mathematics, Sylvester’s criterion is a necessary and sufficient criterion to determine whether a Hermitian matrix is positive-definite. 
* Sylvester's criterion states that a n × n Hermitian matrix M is positive-definite if and only if all the following matrices have a positive determinant:
  - the upper left 1-by-1 corner of M,
  - the upper left 2-by-2 corner of M,
  - the upper left 3-by-3 corner of M
* In other words, all of the leading principal minors must be positive. By using appropriate permutations of rows and columns of M, it can also be shown that the positivity of any nested sequence of n principal minors of M is equivalent to M being positive-definite.


This test tells us whether a matrix is positive definite or not.

For more details check out following: Sylvester's Criterion For Positive Definite Matrices Explained with Worked Example
https://youtu.be/uOpq-CfWMLc

# Method 1: Using Numpy to check Stlvester's Criteria

In [1]:
import numpy as np

In [2]:
#  Generate a random positive-definite matrix. 
def generate_random_pd_matrix(n_dim):
  A=np.random.rand(n_dim, n_dim)
  return np.dot(A, A.transpose()) 
  # Method 2 : we can use the make_spd_matrix() function 
  # from sklearn import datasets
  # npPD = datasets.make_spd_matrix(n_dim, random_state=None)

def check_sylvester_criterion(npPD):
  intSize=max(npPD.shape)
  i=0
  j=1
  while j <= intSize:

    # 1. Calculating determinant value of Upper Left Matrix of size j x j
    npUpperLeftMatrix = npPD[i:j, i:j] 
    npDeterminantValue=round(np.linalg.det(npUpperLeftMatrix), 4)
    #print(f"For Upper left {j} x {j} matrix \n{npUpperLeftMatrix} ")

    # 2. Check the positive determinant condition
    if npDeterminantValue < 0: 
      print(f"For Upper left {j} x {j} matrix Determinant is: {npDeterminantValue} which is Negative")
      return False
      break
    elif j == intSize:         
      print(f"For Upper left {j} x {j} matrix Determinant is: {npDeterminantValue} which is positive")
      return True
    else:                      
      print(f"For Upper left {j} x {j} matrix Determinant is: {npDeterminantValue} which is positive")
    j += 1

def main():

  #1. Randomly generate a positive definite matrix
  n_dim=int(input('Enter size of positive definite matrix to be:'))
  npPD=generate_random_pd_matrix(n_dim)
  print(f"Generated Random Matrix is:\n {npPD}")

  #2. Check Sylvester’s criterion
  print("\nChecking the Sylvester Criteria:")
  bolCriteria = check_sylvester_criterion(npPD)
  if bolCriteria: print("\nTherefore the matrix is Positive Definite Matrix !!!")
  else:           print("\nTherefore the matrix is not Positive Definite Matrix !!!")

  return 

main()

Enter size of positive definite matrix to be:4
Generated Random Matrix is:
 [[0.65914727 0.70921317 0.57569875 1.02161078]
 [0.70921317 1.29433092 0.80509127 0.92191171]
 [0.57569875 0.80509127 0.58386113 0.76793941]
 [1.02161078 0.92191171 0.76793941 1.89503237]]

Checking the Sylvester Criteria:
For Upper left 1 x 1 matrix Determinant is: 0.6591 which is positive
For Upper left 2 x 2 matrix Determinant is: 0.3502 which is positive
For Upper left 3 x 3 matrix Determinant is: 0.0057 which is positive
For Upper left 4 x 4 matrix Determinant is: 0.0001 which is positive

Therefore the matrix is Positive Definite Matrix !!!


References: 
Positive Definite Matrix
1. https://www.youtube.com/watch?v=uOpq-CfWMLc
2. https://stackoverflow.com/questions/41467570/sklearn-doesnt-have-attribute-datasets
3. https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_spd_matrix.html
4. Examples: https://www.programcreek.com/python/example/117638/sklearn.datasets.make_spd_matrix 


## Method 2 using Cholesky 
### (Additional method )

In [4]:
import numpy as np #

def is_pos_def(X):
    
    # function that will check the postive definite condition 
    def check_conditions(A):
        
        #check if the matrix is symmetric
        if np.array_equal(A, A.T):
            
            try:
                ##take a 'Cholesky' decomposition:
                np.linalg.cholesky(A)
                return True
            except np.linalg.LinAlgError:
                return False
        else:
            return False
            
        # for the function explaination please refer to this link: https://stackoverflow.com/questions/16266720/find-out-if-matrix-is-positive-definite-with-numpy
    
    
    if check_conditions(X) == True: 
        print(f"\nMatrix {X} \nis positive definite")
    else: 
        print(f"\nMatrix {X} \nis not positive definite")

In [5]:
# Example 1 Following is not positive definite
A = np.array([[1, -100],[0, 2]]) 
is_pos_def(A)

# Example 2 Positive definite
A = np.array([[2,-1,0],
              [-1, 2, -1],
              [0, -1, 2]]) 
is_pos_def(A)


# Example 3 Positive definite
A = np.array([[2,-1, 2],
              [-1, 2, -1],
              [2, -1, 2]]) 
is_pos_def(A)


Matrix [[   1 -100]
 [   0    2]] 
is not positive definite

Matrix [[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]] 
is positive definite

Matrix [[ 2 -1  2]
 [-1  2 -1]
 [ 2 -1  2]] 
is positive definite
